{% set name = "types-bleach" %}
{% set version = "4.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-bleach-{{ version }}.tar.gz
  sha256: b25662758e1c6f658649715a9323678071aa155493fb57b4501fe50fbd0fac5d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/bleach-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for bleach
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
